services:
  app:
    image: node:18-alpine
    build: .
    command: npm i && npm run start
    volumes:
      - ./:/app/
    ports:
      - 127.0.0.1:1337:1337
    working_dir: /app
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo
#     ports:
#       - 127.0.0.1:27017:27017
#     volumes:
#       - mongodb-data:/data/db

# volumes:
#   mongodb-data: 
